// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HRCDB.Data.HRC
{
    public class Leaderboard
    {
        public string Username { get; set; }
        public string Name { get; set; }
        public int? TotalPoints { get; set; }

        public virtual CompetitorHeartRateZones CompetitorHeartRateZones { get; set; }
    }
}