// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HRCDB.Data.HRC
{
    public partial class ScoreConfig
    {
        public int HeartRateZone { get; set; }
        public int Points { get; set; }
    }
}