// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HRCDB.Data.HRC
{
    public partial class UploadHistory
    {
        public string Id { get; set; }
        public string Username { get; set; }
        public string FileName { get; set; }
        public DateTime UploadDate { get; set; }
        public int? PointChange { get; set; }
    }
}