// <auto-generated />
using BlazorHRC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorHRC.Migrations
{
    [DbContext(typeof(HRCContext))]
    partial class HRCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorHRC.Data.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zone1LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone1UpperBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone2LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone2UpperBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone3LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone3UpperBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone4LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone4UpperBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone5LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("Zone5UpperBound")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorHRC.Data.Entities.Workout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
